const BASE_API_URL = process.env.NEXT_PUBLIC_API;
const MOCKAROO_API_KEY = process.env.NEXT_PUBLIC_MOCKAROO_API_KEY;
const API_KEY = process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY;
const AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
const DATABASE_URL = process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL;
const PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
const MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
const APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
const MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID;

export {
  BASE_API_URL,
  API_KEY,
  MOCKAROO_API_KEY,
  AUTH_DOMAIN,
  DATABASE_URL,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
  APP_ID,
  MEASUREMENT_ID,
};
